[envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest-randomly",
  "tomli>=1.2.2; python_version < '3.11'",
]
post-install-commands = [
  "pip install {verbosity:flag:-1} -e ./tests/mocks/mock-a",
  "pip install {verbosity:flag:-1} -e ./tests/mocks/mock-b",
  "pip install {verbosity:flag:-1} -e ./tests/mocks/mock-c",
]
[envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report --show-missing",
]
cov = [
  "test-cov",
  "cov-report",
]

[[envs.all.matrix]]
python = ["3.7", "3.8", "3.9", "3.10", "3.11"]

[envs.lint]
detached = true
dependencies = [
  "black>=22.10.0",
  "mypy>=0.991",
  "ruff>=0.0.166",
]
[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src/extension tests}"
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]

[envs.docs]
dependencies = [
  "mkdocs~=1.3.0",
  "mkdocs-material~=8.3.1",
  # Plugins
  "mkdocs-minify-plugin~=0.5.0",
  "mkdocs-git-revision-date-localized-plugin~=1.0.1",
  "mkdocstrings-python~=0.7.0",
  # Extensions
  "pymdown-extensions~=9.4.0",
  "mkdocs-material-extensions~=1.0.3",
  # Necessary for syntax highlighting in code blocks
  "pygments~=2.12.0",
]
[envs.docs.env-vars]
SOURCE_DATE_EPOCH = "1580601600"
[envs.docs.scripts]
build = "mkdocs build --clean --strict {args}"
serve = "mkdocs serve --dev-addr localhost:8000 {args}"
