site_name: extensionlib
site_description: The toolkit for building Python extension modules
site_author: Ofek Lev
site_url: https://ofek.dev/extensionlib/
repo_name: ofek/extensionlib
repo_url: https://github.com/ofek/extensionlib
edit_uri: blob/master/docs
copyright: 'Copyright &copy; Ofek Lev 2022-present'

docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/tools
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - content.tabs.link

nav:
  - About: index.md
  - Usage:
    - Config: config.md
    - Builders: builders.md
    - Runners: runners.md
  - Reference:
    - Interface: interface.md
    - Utilities: utilities.md
  - Status:
    - History: history.md
    - Users: users.md

plugins:
  # Built-in
  - search:
  # Extra
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            # Headings
            show_root_heading: true
            show_root_full_path: false
            # Docstrings
            show_if_no_docstring: true
            # Signatures/annotations
            show_signature_annotations: true
            # Other
            show_bases: false
            show_source: false
      watch:
        - src/extension

markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: pypa
      repo: extensionlib
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/.snippets
      auto_append:
        - links.txt
        - abbrs.txt
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ofek
    - icon: fontawesome/solid/blog
      link: https://ofek.dev/words/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Ofekmeister
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ofeklev/
extra_css:
  - assets/css/custom.css
  - https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css
