name: build docs

on:
  workflow_call:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: build-docs-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch all history for applying timestamps to every page
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Build documentation
      run: hatch run docs:build

    - uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: site
